<div class="card"></div>
    <div class="jumbotron text-center" style="padding: 45px;margin: 200px;border-radius:25px">
        <h2 data-aos="fade-down" data-aos-duration="900">Test your knowlegde.</h2>
        <p class="lead text-break" data-aos="fade-down" data-aos-duration="900" data-aos-delay="800">Take the five question FBLA quiz today and start earning badges, perks, and more! The quiz is 5 questions long and the questions are randomly generated.</p>
        <p>
        <form method = "post">
		<a href = "<?php echo url('questions') ?>" class="btn btn-primary btn-lg btn-round" role="button" data-aos="fade" data-aos-duration="950" data-aos-delay="1600">Lets Start!</a>
        </form>
        </p>
    </div>
