<div class = "container">
 <div class="row">
    <div class="col s12 m12">
      <div class="card white" style = "margin-top:25vh">
        <div class="card-content">
          <span class="card-title">FBLA Quiz</span>
          <p>Test your knowledge with our FBLA Quiz. Download our app, earn badges, and more. This web application is proudly open sourced on GitHub.</p>
        </div>
        <div class="card-action">
            <a href = "<?php echo url('register') ?>" class="waves-effect waves-light btn blue"><i class="material-icons left">app_registration</i> Create an account</a>
            <a href = "<?php echo url('register') ?>" class="waves-effect waves-light btn pink darken-1"><i class="material-icons left">smartphone</i> Download our App</a>

        </div>
      </div>
</div>
</div>
</div>
