<?php notify() ?>
<div class = "container">
<div clas = "row">
<div class = "col-md-6 offset-3">
<div class="login-form m-5">
    <form method="post">
        <h2 class="text-center">Log in</h2>       
        <div class="form-group">
            <input type="email" name = "email" class="form-control" placeholder="Email" required="required">
        </div>
        <div class="form-group">
            <input type="password" name = "password" class="form-control" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" name = "login" class="btn btn-primary btn-block">Log in</button>
        </div>  
    </form>
    <p class="text-center">Dont have an account? <a href="<?php echo url('register') ?>">Create an Account</a>.</p>
</div>
</div>
</div>
</div>