<?php notify() ?>
<div class = "container">
<div class = "row">
    <div class = "col-md-5 offset-3">
        <div class = "card">
            <div class = "card-header">
                <div class = "card-title">Login</div>
            </div>
            <div class = "card-body m-3">
            <form method = "post">
            <div class = "form group">
                <div class = "col-md-8">
                <input type = "email" class = "form-control" placeholder = "Email" name = "email" required>
                </div>
            </div>
            <div class = "form group">
            <div class = "col-md-8">
                <input type = "password" class = "form-control" placeholder = "Password" name = "password" required>
            </div>
            </div>
            <button type = "submit" class = "btn btn-primary" name = "login">Login</button>
            </form>
            </div>
        </div>
    </div>
</div>
</div>