<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FBLA Quiz</title>
  <meta name="author" content="Bryan Lawless">
  <meta name="description" content="Take the quiz and find out how much you know about FBLA. The quiz is five questions long. You will also recieve a score at the end.">
  <meta name="keywords" content="fbla,quiz,quizes">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">

  <meta name="apple-mobile-web-app-status-bar" content="#aa7700">
  <meta name="theme-color" content="black">
  <link rel="manifest" href="<?php echo SITE_URL . 'manifest.json' ?>">

  <link href = "<?php echo  SITE_URL . ASSETS_PATH . 'css/style.css' ?>" media="screen" rel = "stylesheet">

  <?php if(\FBLA\Routing\Routing::$controller_key == 'info'): ?>
  <link href = "<?php echo SITE_URL . ASSETS_PATH . 'css/print.css' ?>" rel = "stylesheet">
  <?php endif ?>

  <script src = "<?php echo SITE_URL . ASSETS_PATH .  'js/script.js' ?>"></script>

<style>
::-webkit-scrollbar {
    display: none !important;
}

<?php if(\FBLA\Routing\Routing::$controller_key == 'index'): ?>
.ball {
  position: absolute;
  border-radius: 150%;
  opacity: 0.5;
  z-index: -1;
}
<?php endif ?>

body {
   display: flex;
   min-height: 100vh;
   flex-direction: column;
 }

 main {
   flex: 1 0 auto;
 }

</style>

  </head>

  <body>

   <?php notify() ?>

   <?= $this->views['menu'] ?>

  <main>
   <?= $this->views['content'] ?>
  </main>

   <?= $this->views['footer'] ?>

</body>
<script>
M.AutoInit();
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}

window.addEventListener('load', () => {
 registerSW();
});

async function registerSW() {
 if ('serviceWorker' in navigator) {
   try {
     await navigator
           .serviceWorker
           .register('<?php echo ROOT_PATH . 'service_worker.js' ?>');
   }
   catch (e) {
     console.log('Loaded the FBLA PWA Service Worker.');
   }
 }
}

<?php if(\FBLA\Routing\Routing::$controller_key == 'index'): ?>
const colors = ["#f54242", "#4287f5"];

const numBalls = 90;
const balls = [];

for (let i = 0; i < numBalls; i++) {
  let ball = document.createElement("div");
  ball.classList.add("ball");
  ball.style.background = colors[Math.floor(Math.random() * colors.length)];
  ball.style.left = `${Math.floor(Math.random() * 100)}vw`;
  ball.style.top = `${Math.floor(Math.random() * 100)}vh`;
  ball.style.transform = `scale(${Math.random()})`;
  ball.style.width = `${Math.random()}em`;
  ball.style.height = ball.style.width;

  balls.push(ball);
  document.body.append(ball);
}

// Keyframes
balls.forEach((el, i, ra) => {
  let to = {
    x: Math.random() * (i % 2 === 0 ? -11 : 11),
    y: Math.random() * 12
  };

  let anim = el.animate(
    [
      { transform: "translate(0, 0)" },
      { transform: `translate(${to.x}rem, ${to.y}rem)` }
    ],
    {
      duration: (Math.random() + 1) * 2000, // random duration
      direction: "alternate",
      fill: "both",
      iterations: Infinity,
      easing: "ease-in-out"
    }
  );
});
<?php endif ?>
</script>
</html>
