<?php notify() ?>
<div class="row container padtop80" style="min-height:100vh;margin-top:100px;">
   <div class="col s12 padtop40">
    <div class="col m6 offset-m3 s12 z-depth-1 padtop10 ">
     <div class="lid">
      <form method = "post">
      <div class="input-field col s12">
       <input placeholder="John Doe" id="email" type="text" name = "name" class="validate" autocomplete="off"/>
       <label for="name">Name</label>
      </div>
      <div class="input-field col s12">
       <input placeholder="johnDoe345@mail.com" id="email" type="email" name = "email" class="validate" autocomplete="off"/>
       <label for="email">Email</label>
      </div>
      <div class="input-field col s12">
       <input id="password" type="password" name = "password" class="validate" autocomplete="off"/>
       <label for="password">Password</label>
      </div>
      <div class="input-field col s12">
       <input id="repeat-password" type="password" name = "repeat-password" class="validate" autocomplete="off" />
       <label for="repeat-password">Repeat Password</label>
      </div>
      <div class="input-field col s12 fax_number">
      <input type = "text" name = "fax_number" value = "<?php echo create_encoded_timestamp() ?>" tabindex="-1" autocomplete="off">
      </div>
      <p class="padleft10 remx">
        <button type = "submit" name = "register" class = "btn blue">Register</button>
      </p>
     </form>
     </div>
    </div>
   </div>
  </div>
