 <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
           <a href = "../" class = "navbar-brand text-white">FBLA Quiz</a>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav ml-auto">
                <?php if(is_logged_in() == false){ ?>
                <li class="nav-item">
                    <a class="nav-link ml-auto" href="<?php echo url('login') ?>">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ml-auto" href="<?php echo url('register') ?>">Register</a>
                </li>
                <?php }elseif(FBLA\Routing\Routing::$controller_key !== 'questions'){ ?>
                    <div class="dropdown">
                        <button class="btn btn-info btn-neutral dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                             <i class = "fas fa-compass"></i> <?php echo FBLA\UserData\UserData::userdata('name') ?>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <li><a class="dropdown-item" href="<?php echo url('questions') ?>"><i class = "fas fa-plus-circle"></i> New Quiz</a></li>
                        <li><a class="dropdown-item" href="<?php echo url('dashboard') ?>"><i class = "fas fa-columns"></i> Dashboard</a></li>
                        <li><a class="dropdown-item" href="<?php echo url('logout') ?>"><i class = "fas fa-sign-out-alt"></i> Logout</a></li>
                    </ul>
                    </div>
                <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</nav>