 <nav class="navbar navbar-light navbar-expand-md shadow-sm custom-header" style="background-color: rgb(255,255,255);">
        <div class="container-fluid">
            <div><a class="navbar-brand" href="<?php echo url('') ?>" style="color: rgb(223,74,64);font-family: 'Alfa Slab One', cursive;background-color: rgb(255,255,255);">FBLA<span style="color: rgb(64,147,223); font-family: 'Alfa Slab One';">Quiz</span> </a><button data-toggle="collapse" class="navbar-toggler"
                    data-target="#navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button></div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav ml-auto">
                <?php if(is_logged_in() == false){ ?>
                <li class="nav-item">
                    <a class="nav-link ml-auto" href="<?php echo url('login') ?>">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ml-auto" href="<?php echo url('register') ?>">Register</a>
                </li>
                <?php }elseif(FBLA\Routing\Routing::$controller_key !== 'questions'){ ?>
                    <div class="btn-group dropleft">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class = "fas fa-compass"></i>
                    </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="<?php echo url('questions') ?>"><i class = "fas fa-plus-circle"></i> New Quiz</a>
                    <a class="dropdown-item" href="<?php echo url('dashboard') ?>"><i class = "fas fa-star"></i> See Quiz Scores</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?php echo url('logout') ?>"><i class = "fas fa-sign-out-alt"></i> Logout</a>
                </div>
                </div>
                <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</nav>