 <nav class="navbar navbar-light navbar-expand-md shadow-sm custom-header" style="background-color: rgb(255,255,255);">
        <div class="container-fluid">
            <div><a class="navbar-brand" href="<?php echo url('') ?>" style="color: rgb(223,74,64);font-family: 'Alfa Slab One', cursive;background-color: rgb(255,255,255);">FBLA<span style="color: rgb(64,147,223); font-family: 'Alfa Slab One';">Quiz</span> </a><button data-toggle="collapse" class="navbar-toggler"
                    data-target="#navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button></div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav links">
					<div class = "nav-item ml-auto">
					<iframe src="https://ghbtns.com/github-btn.html?user=Atom345&repo=FBLA-Quiz-Project&type=star&count=true&size=large" frameborder="0" scrolling="0" width="170" height="30" title="GitHub"></iframe>
                    </div>
					<li class="nav-item" role="presentation"></li>
                </ul>
                <ul class="nav navbar-nav ml-auto"></ul>
            </div>
        </div>
    </nav>