<?php

get_five_recent_completed_quizes(master_key('decrypt', $_COOKIE['loggedin']));

?>
<div class = "container">
<div class = "row">
<div class = "col-md-12">
<div class = "card m-2">
<div class = "card-header">
    <div class = "card-title"><h4>Welcome back, <?php echo FBLA\UserData\UserData::userdata('name') ?></h4></div>
</div>
<div class = "card-body">
<p>We have assembled some quiz stats for you:</p>
<small class = "text-muted">The stats below focus on the five of the most recent quizes that you have taken.</small>
<div id="chart-container"></div>
</div>
</div>
</div>
</div>
</div>
<script>

Highcharts.chart('chart-container', {

title: {
    text: 'Quiz stats for  <?php echo FBLA\UserData\UserData::userdata('name') ?>'
},

yAxis: {
    title: {
        max: 5,
        text: 'Quiz Score'
    }
},

xAxis: {
    accessibility: {
        rangeDescription: 'Quiz Date'
    }
},

legend: {
    layout: 'vertical',
    align: 'right',
    verticalAlign: 'middle'
},

plotOptions: {
    series: {
        label: {
            connectorAllowed: false
        },
        pointStart: 2010
    }
},

series: [{
    name: 'Quiz Score',
    data: [1, 2, 3, 4, 5, 1, 5, 2]
}],

responsive: {
    rules: [{
        condition: {
            maxWidth: 500
        },
        chartOptions: {
            legend: {
                layout: 'horizontal',
                align: 'center',
                verticalAlign: 'bottom'
            }
        }
    }]
}

});
</script>