<?php

$quiz = get_five_recent_completed_quizes(\FBLA\UserData\UserData::userdata('user_id'));

?>
<div class = "container">
<div class = "row">
<div class = "col-md-12">
<div class = "card m-2">
<div class = "card-header">
    <div class = "card-title"><h4>Welcome back, <?php echo FBLA\UserData\UserData::userdata('name') ?></h4></div>
</div>
<div class = "card-body">
<?php if($data->quiz_count > 4){ ?>
<p>We have assembled some quiz stats for you:</p>
<ul>
<li>Number of quizes taken: <?php echo count_quizes(FBLA\UserData\UserData::userdata('user_id')) ?></li>
<li>Failed Quizes: <?php echo count_failed_quizes(FBLA\UserData\UserData::userdata('user_id')) ?> (0/5)</li>
<li>Total amount of questions: <?php echo count_global_questions(FBLA\UserData\UserData::userdata('user_id')) ?></li>
<ul>
<?php }else{ ?>
    <div class="alert alert-primary" role="alert">
        When you finish 5 quizes, we can start gauging your progress.
    </div>
<?php } ?>
</div>
</div>
<?php if(is_admin(FBLA\UserData\UserData::userdata('user_id')) == true){ ?>
<div class = "card m-3">
<div class = "card-header">
<div class = "card-title"><h4>Basic Admin Options</h4></div>
</div>
<div class = "card-body">
<div class = "row">
<div class = "col-md-4">
<div class = "card">
<div class = "card-body">
<div class = "form-grup">
<form method = "post">
<button class = "btn btn-info" type = "submit" name = "backup_database">Backup Database</button>
</form>
<br>
<small class = "text-muted">Backing up your database will create a downloadable copy for which you can save.</small>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<?php } ?>
<div class = "card m-3">
<div class = "card-header">
<div class = "card-title"><h4>Badges</h4></div>
</div>
<div class = "card-body">
<div class = "card-text">Badges can be earned by taking more quizes and leveling up. Grow your knowlegde about FBLA and earn bragging rights.</div>
<br>
<?php echo $data->badge ?>
</div>
</div>
<div class = "card m-3">
<div class = "card-header">
<div class = "card-title"><h4>Quiz List</h4></div>
</div>
<div class = "card-body">
<table class="table">
    <thead>
        <tr>
            <th>Score</th>
            <th>Date Taken</th>
        </tr>
    </thead>
    <tbody>
        <?php
	        $users_result = FBLA\Database\Database::$db->query("SELECT * FROM `quiz_progress` WHERE user_id=".\FBLA\UserData\UserData::userdata('user_id')."");
	        while($row = $users_result->fetch_assoc()){ ?>
             <tr>
            <td><?php echo $row['score'] ?></td>
            <td><?php echo $row['quiz_timestamp'] ?></td>
            </tr>
            <?php } ?>
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>